import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-full lg:h-full">
      <body className="grid grid-cols-1 lg:grid-cols-desktop grid-rows-1 h-full overflow-auto lg:overflow-hidden ">
        {children}
      </body>
    </html>
  );
}
